site_name: Fluxomics Data Model
site_description: Universal format converter for 13C-MFA data
use_directory_urls: False
theme:
  name: "material"
  features:
    - content.code.copy
    - navigation.sections
repo_url: https://github.com/dtu-qmcm/fluxomics_data_model
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [src/fluxomics_data_model]
          options:
            show_bases: false
            docstring_style: sphinx
            members_order: source
            group_by_category: false
            filters: ["!^_"]

markdown_extensions:
  - admonition
  - pymdownx.superfences
  - pymdownx.tabbed
  - attr_list

nav:
  - Home: 'index.md'
  - Getting Started: 'getting_started.md'
  - Supported Formats: 'formats.md'
  - Contributing: 'contributing.md'
  - API:
    - Core: 'api/core.md'
    - Model: 'api/model.md'
    - Experiment: 'api/experiment.md'
    - IO: 'api/io.md'
