"""
MTF (Metabolic Text Format) writer for influx_si format.

MTF is a multi-file format used by influx_si for 13C metabolic flux analysis.
Each model consists of multiple files with a shared basename:
    - .netw: Network definition (reactions with atom mappings)
    - .linp: Label input (tracer specifications)
    - .miso: MS isotopomer measurements
    - .mflux: Flux measurements
    - .cnstr: Constraints (NET and XCH)
    - .tvar: Variable types and starting values
    - .opt: Options/command arguments
"""

from pathlib import Path
from typing import Optional, Dict, List, Tuple
from collections import defaultdict

from ..core.core import FluxomicsDataModel, Experiments
from ..model.atom_mapping import AtomMapping


class MTFWriter:
    """Writer for MTF (Metabolic Text Format) files used by influx_si."""

    def __init__(self):
        self._model: Optional[FluxomicsDataModel] = None
        self._experiment: Optional[Experiments] = None

    def write(
        self,
        model: FluxomicsDataModel,
        base_path: str,
        experiment_name: Optional[str] = None,
    ) -> None:
        """
        Write FluxomicsDataModel to MTF files.

        Args:
            model: FluxomicsDataModel to write
            base_path: Path to base filename (without extension).
                       For example: "output/e_coli" will create
                       "output/e_coli.netw", "output/e_coli.linp", etc.
            experiment_name: Name of experiment to write. If None and model
                            has a single experiment, uses that. If None and
                            model has multiple experiments, raises ValueError.
        """
        self._model = model
        base_path = Path(base_path)

        # Select experiment
        if experiment_name:
            self._experiment = model.get_experiments(experiment_name)
            if not self._experiment:
                raise ValueError(f"Experiment '{experiment_name}' not found")
        elif len(model.experiments) == 1:
            self._experiment = model.experiments[0]
        elif len(model.experiments) > 1:
            raise ValueError(
                "Multiple experiments exist. Please specify experiment_name."
            )
        else:
            self._experiment = None

        # Ensure output directory exists
        base_path.parent.mkdir(parents=True, exist_ok=True)

        # Write each file
        self._write_netw(base_path.with_suffix(".netw"))

        if self._experiment and self._experiment.tracers:
            self._write_linp(base_path.with_suffix(".linp"))

        if self._experiment and self._experiment.measurement:
            if self._experiment.measurement.model.labeling_measurement:
                self._write_miso(base_path.with_suffix(".miso"))
            if self._experiment.measurement.model.flux_measurement:
                self._write_mflux(base_path.with_suffix(".mflux"))

        if model.constraints or (
            self._experiment and self._experiment.constraints
        ):
            self._write_cnstr(base_path.with_suffix(".cnstr"))

        if self._experiment and self._experiment.simulation:
            self._write_tvar(base_path.with_suffix(".tvar"))

    def _write_netw(self, filepath: Path) -> None:
        """
        Write .netw file containing reaction network with atom mappings.

        Format: reaction_id: substrate (ATOMS) + substrate (atoms) ->
        product (ATOMS)
        """
        lines = []
        lines.append("# Network definition")
        lines.append("# Generated by fluxomics_data_model")
        lines.append("#")

        # Group reactions by pathway if available
        reactions_by_pathway: Dict[str, List] = defaultdict(list)
        for reaction in self._model.model.reactions:
            pathway = getattr(reaction, "pathway", None) or "Other"
            reactions_by_pathway[pathway].append(reaction)

        for pathway, reactions in reactions_by_pathway.items():
            lines.append(f"# {pathway}")
            lines.append("# " + "-" * 60)

            for reaction in reactions:
                line = self._format_reaction(reaction)
                lines.append(line)

            lines.append("#")

        with open(filepath, "w", encoding="utf-8") as f:
            f.write("\n".join(lines) + "\n")

    def _format_reaction(self, reaction) -> str:
        """Format a single reaction line for .netw file."""
        rxn_id = reaction.id
        reversible = reaction.reversibility

        # Get atom mapping if exists
        atom_mapping = self._model.model.atom_mappings.get(rxn_id)

        # Build reactant and product strings
        reactants_str = self._format_compounds(
            reaction.reactants, atom_mapping, is_reactant=True
        )
        products_str = self._format_compounds(
            reaction.products, atom_mapping, is_reactant=False
        )

        # Build arrow based on reversibility
        arrow = "<->" if reversible else "->>"

        # Handle reactions with no products (drains)
        if not reaction.products:
            return f"{rxn_id}: {reactants_str} {arrow}"

        return f"{rxn_id}: {reactants_str} {arrow} {products_str}"

    def _format_compounds(
        self,
        compounds: List[str],
        atom_mapping: Optional[AtomMapping],
        is_reactant: bool,
    ) -> str:
        """Format compounds with atom mappings for .netw file."""
        if not compounds:
            return ""

        parts = []
        compound_counts: Dict[str, int] = {}

        for cpd_id in compounds:
            # Track instance for repeated compounds
            compound_counts[cpd_id] = compound_counts.get(cpd_id, 0) + 1
            instance = compound_counts[cpd_id]

            # Get atom letters if atom mapping exists
            atoms_str = ""
            if atom_mapping and atom_mapping.maps:
                # Get the first (or only) atom map
                atom_map = next(iter(atom_mapping.maps.values()))

                if is_reactant:
                    # For reactants, collect atoms that are sources
                    atoms = self._get_reactant_atoms(atom_map, cpd_id, instance)
                else:
                    # For products, collect atoms that are targets
                    atoms = self._get_product_atoms(atom_map, cpd_id, instance)

                if atoms:
                    atoms_str = f" ({atoms})"

            parts.append(f"{cpd_id}{atoms_str}")

        return " + ".join(parts)

    def _get_reactant_atoms(self, atom_map, cpd_id: str, instance: int) -> str:
        """Get atom letter notation for a reactant compound."""
        # Build a mapping from (cpd, instance, atom_idx) -> letter
        # based on the product side mappings

        # First, collect all reactant atoms used in products
        reactant_atoms: Dict[Tuple[str, int, int], str] = {}
        letters = (
            "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
        )
        letter_idx = 0

        # Iterate through all product atoms in order
        sorted_product_atoms = sorted(
            atom_map.mapping.keys(), key=lambda a: (a.mol, a.instance, a.index)
        )

        # Assign letters based on first appearance in products
        for prod_addr in sorted_product_atoms:
            src_addr = atom_map.mapping[prod_addr]
            key = (src_addr.mol, src_addr.instance, src_addr.index)
            if key not in reactant_atoms:
                if letter_idx < len(letters):
                    reactant_atoms[key] = letters[letter_idx]
                    letter_idx += 1

        # Now collect atoms for this specific reactant
        atoms = []
        for (mol, inst, idx), letter in sorted(
            reactant_atoms.items(), key=lambda x: x[0][2]
        ):
            if mol == cpd_id and inst == instance:
                atoms.append((idx, letter))

        # Sort by atom index and return letters
        atoms.sort(key=lambda x: x[0])
        return "".join(letter for _, letter in atoms)

    def _get_product_atoms(self, atom_map, cpd_id: str, instance: int) -> str:
        """Get atom letter notation for a product compound."""
        # Same letter assignment as reactants
        reactant_atoms: Dict[Tuple[str, int, int], str] = {}
        letters = (
            "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
        )
        letter_idx = 0

        sorted_product_atoms = sorted(
            atom_map.mapping.keys(), key=lambda a: (a.mol, a.instance, a.index)
        )

        for prod_addr in sorted_product_atoms:
            src_addr = atom_map.mapping[prod_addr]
            key = (src_addr.mol, src_addr.instance, src_addr.index)
            if key not in reactant_atoms:
                if letter_idx < len(letters):
                    reactant_atoms[key] = letters[letter_idx]
                    letter_idx += 1

        # Now collect atoms for this specific product in product order
        atoms = []
        for prod_addr in sorted_product_atoms:
            if prod_addr.mol == cpd_id and prod_addr.instance == instance:
                src_addr = atom_map.mapping[prod_addr]
                key = (src_addr.mol, src_addr.instance, src_addr.index)
                letter = reactant_atoms.get(key, "?")
                atoms.append((prod_addr.index, letter))

        # Sort by atom index and return letters
        atoms.sort(key=lambda x: x[0])
        return "".join(letter for _, letter in atoms)

    def _write_linp(self, filepath: Path) -> None:
        """
        Write .linp file containing tracer specifications.

        Format (TSV): Id\tComment\tSpecie\tIsotopomer\tValue
        """
        lines = []
        lines.append("Id\tComment\tSpecie\tIsotopomer\tValue")

        if self._experiment and self._experiment.tracers:
            for tracer in self._experiment.tracers:
                metabolite = tracer.metabolite
                for label in tracer.labels:
                    isotopomer = label.labeled_pattern
                    fraction = label.fraction
                    lines.append(f"\t\t{metabolite}\t{isotopomer}\t{fraction}")

        with open(filepath, "w", encoding="utf-8") as f:
            f.write("\n".join(lines) + "\n")

    def _write_miso(self, filepath: Path) -> None:
        """
        Write .miso file containing MS isotopomer measurements.

        Format (TSV):
        Id\tComment\tSpecie\tFragment\tDataset\tIsospecies\tValue\tSD\tTime
        """
        lines = []
        lines.append(
            "Id\tComment\tSpecie\tFragment\tDataset\tIsospecies\tValue\tSD\tTime"
        )

        if (
            self._experiment
            and self._experiment.measurement
            and self._experiment.measurement.model.labeling_measurement
        ):
            labeling = self._experiment.measurement.model.labeling_measurement
            data = (
                self._experiment.measurement.data.data
                if self._experiment.measurement.data
                else []
            )

            # Build a lookup from datum id to datum
            {d.id: d for d in data}

            for group in labeling.groups:
                # Parse group expression to get metabolite and fragment
                expression = (
                    group.expression.textual if group.expression else group.id
                )

                # Parse expression like "Ala[2,3]" or "AKG"
                metabolite, fragment = self._parse_ms_expression(expression)

                # Find all data points for this group
                # Group ID format varies, so we search for matching data
                for datum in data:
                    if datum.id.startswith(group.id):
                        # Extract isospecies from datum id
                        # (e.g., "group:M0" -> "M0")
                        parts = datum.id.split(":")
                        isospecies = parts[-1] if len(parts) > 1 else ""

                        time_str = (
                            str(datum.time) if datum.time is not None else ""
                        )

                        lines.append(
                            f"\t\t{metabolite}\t{fragment}\tinst\t{isospecies}\t"
                            f"{datum.value}\t{datum.stddev}\t{time_str}"
                        )

        with open(filepath, "w", encoding="utf-8") as f:
            f.write("\n".join(lines) + "\n")

    def _parse_ms_expression(self, expression: str) -> Tuple[str, str]:
        """Parse MS expression like 'Ala[2,3]' into (metabolite, fragment)."""
        import re

        # Match patterns like "Ala[2,3]" or "Ala[2+3]" or "AKG"
        match = re.match(r"^(\w+)(?:\[([^\]]+)\])?$", expression)
        if match:
            metabolite = match.group(1)
            fragment_spec = match.group(2)

            if fragment_spec:
                # Convert "2+3" or "2,3" format to "2,3"
                fragment = fragment_spec.replace("+", ",")
            else:
                # Full molecule - need to get atom count from metabolite
                metabolite_obj = self._model.model.metabolites.get(metabolite)
                if metabolite_obj and metabolite_obj.atoms:
                    # Generate full fragment like "1,2,3,4,5"
                    fragment = ",".join(
                        str(i) for i in range(1, metabolite_obj.atoms + 1)
                    )
                else:
                    fragment = ""

            return metabolite, fragment

        return expression, ""

    def _write_mflux(self, filepath: Path) -> None:
        """
        Write .mflux file containing flux measurements.

        Format (TSV): Id\tComment\tFlux\tValue\tSD
        """
        lines = []
        lines.append("Id\tComment\tFlux\tValue\tSD")

        if (
            self._experiment
            and self._experiment.measurement
            and self._experiment.measurement.model.flux_measurement
        ):
            flux_meas = self._experiment.measurement.model.flux_measurement
            data = (
                self._experiment.measurement.data.data
                if self._experiment.measurement.data
                else []
            )

            # Build a lookup from datum id to datum
            datum_lookup = {d.id: d for d in data}

            for net_flux in flux_meas.net_fluxes:
                flux_id = net_flux.id
                expression = (
                    net_flux.expression.textual
                    if net_flux.expression
                    else flux_id
                )

                # Find matching datum
                datum = datum_lookup.get(flux_id)
                if datum:
                    lines.append(
                        f"\t\t{expression}\t{datum.value}\t{datum.stddev}"
                    )

        with open(filepath, "w", encoding="utf-8") as f:
            f.write("\n".join(lines) + "\n")

    def _write_cnstr(self, filepath: Path) -> None:
        """
        Write .cnstr file containing constraints.

        Format (TSV): Id\tComment\tKind\tFormula\tOperator\tValue
        """
        lines = []
        lines.append("Id\tComment\tKind\tFormula\tOperator\tValue")

        # Collect constraints from model level
        constraints = self._model.constraints

        # Also check experiment-level constraints
        if self._experiment and self._experiment.constraints:
            if constraints:
                # Merge constraints (experiment takes precedence)
                pass  # For now, just use model constraints
            else:
                constraints = self._experiment.constraints

        if constraints:
            # Write NET constraints
            if constraints.net and constraints.net.formulas:
                for formula in constraints.net.formulas:
                    expression = formula.expression
                    # Parse expression to extract operator and value
                    op, lhs, rhs = self._parse_constraint_expression(expression)
                    lines.append(f"\t\tNET\t{lhs}\t{op}\t{rhs}")

            # Write XCH constraints
            if constraints.xch and constraints.xch.formulas:
                for formula in constraints.xch.formulas:
                    expression = formula.expression
                    op, lhs, rhs = self._parse_constraint_expression(expression)
                    lines.append(f"\t\tXCH\t{lhs}\t{op}\t{rhs}")

        with open(filepath, "w", encoding="utf-8") as f:
            f.write("\n".join(lines) + "\n")

    def _parse_constraint_expression(
        self, expression: str
    ) -> Tuple[str, str, str]:
        """Parse constraint expression into (operator, lhs, rhs)."""
        import re

        # Try to match patterns like "A = B" or "A == B" or "A >= B" or "A <= B"
        match = re.match(r"^(.+?)\s*(==|>=|<=|=)\s*(.+)$", expression)
        if match:
            lhs = match.group(1).strip()
            op = match.group(2)
            rhs = match.group(3).strip()
            return op, lhs, rhs

        # No operator found - return as formula with ==0
        return "==", expression, "0"

    def _write_tvar(self, filepath: Path) -> None:
        """
        Write .tvar file containing variable types and starting values.

        Format (TSV): Id\tComment\tName\tKind\tType\tValue
        """
        lines = []
        lines.append("Id\tComment\tName\tKind\tType\tValue")

        if self._experiment and self._experiment.simulation:
            sim = self._experiment.simulation

            if sim.variables:
                # Write flux values
                for flux_val in sim.variables.flux_values:
                    flux_name = flux_val.flux
                    var_type = flux_val.type or "D"
                    value = flux_val.value if flux_val.value is not None else ""

                    # Determine kind (NET or XCH) based on naming convention
                    # In influx_si, XCH variables are for exchange coefficients
                    kind = "NET"

                    lines.append(
                        f"\t\t{flux_name}\t{kind}\t{var_type}\t{value}"
                    )

                # Write metabolite size values (if any)
                for met_val in sim.variables.metabolitesize_values:
                    met_name = met_val.metabolite
                    var_type = met_val.type or "F"
                    value = met_val.value if met_val.value is not None else ""

                    lines.append(f"\t\t{met_name}\tMETAB\t{var_type}\t{value}")

        with open(filepath, "w", encoding="utf-8") as f:
            f.write("\n".join(lines) + "\n")


def write_mtf(
    model: FluxomicsDataModel,
    base_path: str,
    experiment_name: Optional[str] = None,
) -> None:
    """
    Convenience function to write FluxomicsDataModel to MTF files.

    Args:
        model: FluxomicsDataModel to write
        base_path: Path to base filename (without extension)
        experiment_name: Name of experiment to write (optional)
    """
    writer = MTFWriter()
    writer.write(model, base_path, experiment_name)
